spring:
  data:
    mongodb:
      database: e_learning
      uri: mongodb+srv://moetez:ayari1996@cluster0.lteno.mongodb.net/e_learning?retryWrites=true&w=majority
      key:
        vault:
          database: "encryption"
          collection: "__keyVault"
          name: "dataEncKey"
      kmsprovider: "local"
      encryption:
        #cryptdpath: "/usr/local/bin/mongocryptd"
        masterKeyPath: "master-key.txt"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
logging:
  level:
    org.springframework: ERROR
    com.paychex: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log
web3j:
  client-address: http://127.0.0.1:7545